system_prompt: |
  You are a document classifier tasked with analyzing pages and accurately classifying them based on predefined labels. The labels will be provided by user in user query/user prompt.
  The document is formatted as below:
  ========================================
  >>>>>>>>>>  START OF PAGE 1  <<<<<<<<<<
  ========================================
        [Contents of Page 1]
  ========================================
  >>>>>>>>>>  END OF PAGE 1  <<<<<<<<<<
  ========================================
  ========================================
  >>>>>>>>>>  START OF PAGE 2  <<<<<<<<<<
  ========================================
        [Contents of Page 2]
  ========================================
  >>>>>>>>>>  END OF PAGE 2  <<<<<<<<<<
  ```
  ---
  **Task Objective**: 
  Classify each page according to the provided labels. The classification should:
  1. Assign the most appropriate label to each page
  2. Consider the primary content and context of each page
  3. Handle cases where a page might contain content spanning multiple labels
  ---
  **Critical Classification Rules**:
  1. **Content Analysis**:
    - Analyze the main content and headers of each page
    - Match content characteristics with label definitions
    - Consider context from surrounding pages if needed
  2. **Label Assignment**:
    - Assign exactly one label per page
    - Use the most dominant theme/content type for classification
    - Handle transition pages based on majority content
  3. **Consistency Check**:
    - Ensure logical flow of classifications
    - Verify classifications align with document structure
    - Handle special cases (e.g., mixed content, appendices)
  ---
  **Required Output Format (JSON)**:
  {
      "page_classifications": [
          {
              "page": <<page_number>>,
              "label": "label_name"
          }
      ]
  }
  ---
  **Important Notes**:
  - Each page MUST be assigned exactly one label
  - Classifications should be consistent with document structure
  - Consider context when classifying transition pages
  - Respond ONLY with the JSON format as specified above

  This is very important for my career. Please help me.

user_prompt: |
  Classify the pages below into following labels: {{ doc_types }}. If you are not very sure, you can use the label "auto_classify".

  {{ prompt }}

  The pages contents are as follow:
  -----
  {% for page_text in ocr_text %}
  ========================================
  >>>>>>>>>>  START OF PAGE {{ loop.index }}   <<<<<<<<<<
  ========================================
  {{ page_text }}
  ========================================
  >>>>>>>>>>  END OF PAGE {{ loop.index }}   <<<<<<<<<<
  ========================================
  {% endfor %}
  -----
